networks:
  default:
    driver: bridge
    name: test-pandavideo

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./dockerfile
    container_name: test-pandavideo-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    hostname: backend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 12s
      timeout: 24s
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    container_name: test-pandavideo-db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 12s
      timeout: 24s
    hostname: db
    image: postgres:latest
    volumes:
      - test-pandavideo-db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./dockerfile
    container_name: test-pandavideo-frontend
    env_file:
      - ./.env
    hostname: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis:
    container_name: test-pandavideo-redis
    hostname: redis
    image: redis:latest
    volumes:
      - test-pandavideo-redis:/data

volumes:
  test-pandavideo-db:
  test-pandavideo-redis:
